import { Child, Rule } from "./types";

export const children: Child[] = [
  { id: "lisandro", name: "Lisandro", currency: "pts", color: "#5b21b6" },
  { id: "mila", name: "Mila", currency: "⭐", color: "#0f766e" },
];

export const rules: Rule[] = [
  { id: "l_gain_1", childId: "lisandro", label: "Routine retour collège complète", value: 3, type: "gain" },
  { id: "l_gain_2", childId: "lisandro", label: "Devoirs terminés avant 18h", value: 2, type: "gain" },
  { id: "l_gain_3", childId: "lisandro", label: "Chambre + lit faits le matin", value: 2, type: "gain" },
  { id: "l_gain_4", childId: "lisandro", label: "Téléphone rendu à 20h sans rappel", value: 3, type: "gain" },
  { id: "l_gain_5", childId: "lisandro", label: "Tâche hebdo faite (SDB ou poubelles)", value: 2, type: "gain" },
  { id: "l_gain_6", childId: "lisandro", label: "Attitude coopérative", value: 2, type: "gain" },
  { id: "l_loss_1", childId: "lisandro", label: "Téléphone non rendu à 20h", value: -4, type: "loss" },
  { id: "l_loss_2", childId: "lisandro", label: "Routine retour non faite", value: -3, type: "loss" },
  { id: "l_loss_3", childId: "lisandro", label: "Chambre / lit non faits", value: -2, type: "loss" },
  { id: "l_loss_4", childId: "lisandro", label: "Attitude irrespectueuse", value: -5, type: "loss" },
  { id: "l_loss_5", childId: "lisandro", label: "Téléphone utilisé après 20h", value: -10, type: "loss" },
  { id: "l_reward_1", childId: "lisandro", label: "Choix du film vendredi", value: 0, rewardCost: 10, type: "reward" },
  { id: "l_reward_2", childId: "lisandro", label: "+30 min écrans samedi (tél, console, etc.)", value: 0, rewardCost: 15, type: "reward" },
  { id: "l_reward_3", childId: "lisandro", label: "Sortie avec les amis (2h)", value: 0, rewardCost: 20, type: "reward" },
  { id: "l_reward_4", childId: "lisandro", label: "Argent de poche +5€", value: 0, rewardCost: 30, type: "reward" },
  { id: "l_reward_5", childId: "lisandro", label: "Activité spéciale", value: 0, rewardCost: 50, type: "reward" },
  { id: "m_gain_1", childId: "mila", label: "Exercices ortho faits", value: 3, type: "gain" },
  { id: "m_gain_2", childId: "mila", label: "Chambre + lit faits le matin", value: 2, type: "gain" },
  { id: "m_gain_3", childId: "mila", label: "Goûter préparé seule", value: 1, type: "gain" },
  { id: "m_gain_4", childId: "mila", label: "Douche sans rappel", value: 2, type: "gain" },
  { id: "m_gain_5", childId: "mila", label: "Douche + cheveux sans crise (mer/dim)", value: 3, type: "gain" },
  { id: "m_gain_6", childId: "mila", label: "Tâche hebdo faite (SDB ou courses)", value: 2, type: "gain" },
  { id: "m_gain_7", childId: "mila", label: "Prête à l heure le matin", value: 2, type: "gain" },
  { id: "m_gain_8", childId: "mila", label: "Minuteur douche lancé seule", value: 1, type: "gain" },
  { id: "m_loss_1", childId: "mila", label: "Exercices ortho non faits", value: -3, type: "loss" },
  { id: "m_loss_2", childId: "mila", label: "Chambre non faite", value: -2, type: "loss" },
  { id: "m_loss_3", childId: "mila", label: "Refus douche / crise TOP", value: -3, type: "loss" },
  { id: "m_loss_4", childId: "mila", label: "Comportement irrespectueux", value: -3, type: "loss" },
  { id: "m_reward_1", childId: "mila", label: "Autocollant collection", value: 0, rewardCost: 5, type: "reward" },
  { id: "m_reward_2", childId: "mila", label: "Choix du dessert dimanche", value: 0, rewardCost: 8, type: "reward" },
  { id: "m_reward_3", childId: "mila", label: "30 min dessin animé choisi", value: 0, rewardCost: 10, type: "reward" },
  { id: "m_reward_4", childId: "mila", label: "Activité spéciale avec un parent", value: 0, rewardCost: 15, type: "reward" },
  { id: "m_reward_5", childId: "mila", label: "Invitation amie à la maison", value: 0, rewardCost: 20, type: "reward" },
];
